Updatec build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -266,117 +266,89 @@ jobs:
             # Delete files that may conflict with kernel functionality
             rm -rf ./android/abi_gki_protected_exports*
 
+        
+        - name: 'Verify P'
+          run: |
+            shopt -s globstar
+            TOOLCHAIN_DIR=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}
+             if [ ! -d "$TOOLCHAIN_DIR" ]; then
+              echo " ERROR: El toolchain no existe en la ruta $TOOLCHAIN_DIR"
+              exit 1
+             fi
+             ls -l $TOOLCHAIN_DIR
+             
         - name: 'Generate the kernel .config file'
           working-directory: './kernel-src'
           run: |
             shopt -s globstar
+            export CLANG_DIR=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}
+            export PATH=$CLANG_DIR:$PATH
+
+            export MAKE_ARGS="CC=clang \
+            NM=llvm-nm \
+            CXX=clang++ \
+            AR=llvm-ar \
+            LD=ld.lld \
+            STRIP=llvm-strip \
+            OBJCOPY=llvm-objcopy \
+            OBJDUMP=llvm-objdump \
+            OBJSIZE=llvm-size \
+            READELF=llvm-readelf \
+            HOSTAR=llvm-ar \
+            HOSTLD=ld.lld \
+            HOSTCC=clang \
+            HOSTCXX=clang++ \
+            LLVM=1 \
+            LTO=thin"
+
 
             # Generate kernel config using make
             if [ ${{ github.event.inputs.KERNEL_COMPILER }} == 'Clang/LLVM' ]; then
                 if [ ! -z ${{ github.event.inputs.KERNEL_COMPILER_TOOLCHAIN }} ]; then
-                    make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}clang LLVM=$(realpath ~)/**/compiler-toolchain/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }} LLVM_IAS=1 -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
+                    make ARCH=${{ github.event.inputs.KERNEL_ARCH }} $MAKE_ARGS LLVM_IAS=1 -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
                 else
-                    make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/LLVM-*-Linux-X64/bin)/clang LLVM=$(realpath ~/**/LLVM-*-Linux-X64/bin)/ LLVM_IAS=1 -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
-                fi
-            fi
-
-            if [ ${{ github.event.inputs.KERNEL_COMPILER }} == 'GCC/Binutils' ]; then
-                if [ ! -z ${{ github.event.inputs.KERNEL_COMPILER_TOOLCHAIN }} ]; then
-                    make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}gcc CROSS_COMPILE=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }} -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
-                else
-                    if [ ${{ github.event.inputs.KERNEL_ARCH }} == 'arm' ]; then
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf-gcc CROSS_COMPILE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf- -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
-                    else
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu-gcc CROSS_COMPILE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu- -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
-                    fi
-                fi
-            fi
-
-            if [ ${{ github.event.inputs.KERNEL_COMPILER }} == 'Clang/Binutils' ]; then
-                if [ ! -z ${{ github.event.inputs.KERNEL_COMPILER_TOOLCHAIN }} ]; then
-                    if [ ${{ github.event.inputs.KERNEL_ARCH }} == 'arm' ]; then
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}clang CLANG_TRIPLE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf- CROSS_COMPILE=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }} -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
-                    else
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}clang CLANG_TRIPLE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu- CROSS_COMPILE=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }} -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
-                    fi
-                else
-                    if [ ${{ github.event.inputs.KERNEL_ARCH }} == 'arm' ]; then
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=clang CLANG_TRIPLE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf- CROSS_COMPILE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf- -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
-                    else
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=clang CLANG_TRIPLE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu- CROSS_COMPILE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu- -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
-                    fi
-                fi
-            fi
-
-            if [ ${{ github.event.inputs.KERNEL_COMPILER }} == 'GCC/LLVM' ]; then
-                if [ ! -z ${{ github.event.inputs.KERNEL_COMPILER_TOOLCHAIN }} ]; then
-                    make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}gcc LLVM=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }} LLVM_IAS=1 -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
-                else
-                    if [ ${{ github.event.inputs.KERNEL_ARCH }} == 'arm' ]; then
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf-gcc LLVM=$(realpath ~/**/LLVM-*-Linux-X64/bin)/ LLVM_IAS=1 -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
-                    else
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu-gcc LLVM=$(realpath ~/**/LLVM-*-Linux-X64/bin)/ LLVM_IAS=1 -j$(nproc --all) O=out ${{ github.event.inputs.KERNEL_CONFIGS }}
-                    fi
+                    exit 2
                 fi
             fi
 
             echo 'CONFIG_LOCALVERSION_AUTO=n' >> out/.config
             echo 'CONFIG_KSU_KPROBES_HOOK=n' >> out/.config
 
+    
         - name: 'Build kernel'
           working-directory: './kernel-src'
           run: |
             shopt -s globstar
+            export CLANG_DIR=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}
+            export PATH=$CLANG_DIR:$PATH
 
+            export MAKE_ARGS="CC=clang \
+            NM=llvm-nm \
+            CXX=clang++ \
+            AR=llvm-ar \
+            LD=ld.lld \
+            STRIP=llvm-strip \
+            OBJCOPY=llvm-objcopy \
+            OBJDUMP=llvm-objdump \
+            OBJSIZE=llvm-size \
+            READELF=llvm-readelf \
+            HOSTAR=llvm-ar \
+            HOSTLD=ld.lld \
+            HOSTCC=clang \
+            HOSTCXX=clang++ \
+            LLVM=1 \
+            LTO=thin"
+            
             # Compile using make
             if [ ${{ github.event.inputs.KERNEL_COMPILER }} == 'Clang/LLVM' ]; then
                 if [ ! -z ${{ github.event.inputs.KERNEL_COMPILER_TOOLCHAIN }} ]; then
-                    make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}clang LLVM=$(realpath ~)/**/compiler-toolchain/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }} LLVM_IAS=1 -j$(nproc --all) O=out
+                    make ARCH=${{ github.event.inputs.KERNEL_ARCH }} $MAKE_ARGS LLVM_IAS=1 -j$(nproc --all) O=out
                 else
-                    make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/LLVM-*-Linux-X64/bin)/clang LLVM=$(realpath ~/**/LLVM-*-Linux-X64/bin)/ LLVM_IAS=1 -j$(nproc --all) O=out
+                    exit 3
                 fi
             fi
 
-            if [ ${{ github.event.inputs.KERNEL_COMPILER }} == 'GCC/Binutils' ]; then
-                if [ ! -z ${{ github.event.inputs.KERNEL_COMPILER_TOOLCHAIN }} ]; then
-                    make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}gcc CROSS_COMPILE=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }} -j$(nproc --all) O=out
-                else
-                    if [ ${{ github.event.inputs.KERNEL_ARCH }} == 'arm' ]; then
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf-gcc CROSS_COMPILE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf- -j$(nproc --all) O=out
-                    else
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu-gcc CROSS_COMPILE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu- -j$(nproc --all) O=out
-                    fi
-                fi
-            fi
-
-            if [ ${{ github.event.inputs.KERNEL_COMPILER }} == 'Clang/Binutils' ]; then
-                if [ ! -z ${{ github.event.inputs.KERNEL_COMPILER_TOOLCHAIN }} ]; then
-                    if [ ${{ github.event.inputs.KERNEL_ARCH }} == 'arm' ]; then
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}clang CLANG_TRIPLE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf- CROSS_COMPILE=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }} -j$(nproc --all) O=out
-                    else
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}clang CLANG_TRIPLE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu- CROSS_COMPILE=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }} -j$(nproc --all) O=out
-                    fi
-                else
-                    if [ ${{ github.event.inputs.KERNEL_ARCH }} == 'arm' ]; then
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=clang CLANG_TRIPLE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf- CROSS_COMPILE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf- -j$(nproc --all) O=out
-                    else
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=clang CLANG_TRIPLE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu- CROSS_COMPILE=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu- -j$(nproc --all) O=out
-                    fi
-                fi
-            fi
-
-            if [ ${{ github.event.inputs.KERNEL_COMPILER }} == 'GCC/LLVM' ]; then
-                if [ ! -z ${{ github.event.inputs.KERNEL_COMPILER_TOOLCHAIN }} ]; then
-                    make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }}gcc LLVM=$(realpath ~/**/compiler-toolchain)/${{ github.event.inputs.KERNEL_COMPILER_PREFIX }} LLVM_IAS=1 -j$(nproc --all) O=out
-                else
-                    if [ ${{ github.event.inputs.KERNEL_ARCH }} == 'arm' ]; then
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-arm-none-linux-gnu*/bin)/arm-none-linux-gnueabihf-gcc LLVM=$(realpath ~/**/LLVM-*-Linux-X64/bin)/ LLVM_IAS=1 -j$(nproc --all) O=out
-                    else
-                        make ARCH=${{ github.event.inputs.KERNEL_ARCH }} CC=$(realpath ~/**/arm-gnu-toolchain-*-x86_64-aarch64-none-linux-gnu*/bin)/aarch64-none-linux-gnu-gcc LLVM=$(realpath ~/**/LLVM-*-Linux-X64/bin)/ LLVM_IAS=1 -j$(nproc --all) O=out
-                    fi
-                fi
-            fi
-
+        
         - name: 'Organize boot artifacts'
           working-directory: './kernel-src'
           run: |
